### PR TITLE
Dev Len is Best Len

### PR DESCRIPTION
**Pull request by V2LenKagamine**
Adds a model of "Len Kagamine" to the game.
AFAIK, shouldn't be a way of obtaining him, only a dev can spawn him in.
I may not deserve this model quite yet, but maybe one day, when I have coded more and done things for the server, Maybe then can someone give me the present of this fitting model for my name.
"We already got miku, here comes our boi len!"
**_Now where is his sister I wonder?_**

Model is tested and working, ragdoll, arms and all.
Model by CaptainBigButt, just like the miku model.

### CODE REVIEW

**Comment by 508droid** [comment]
> I may not deserve this model quite yet, but maybe one day, when I have coded more and done things for the server, 

dont even start.
requires community vote and approval

**Comment by V2LenKagamine** [comment]
> > I may not deserve this model quite yet, but maybe one day, when I have coded more and done things for the server,
> 
> dont even start. requires community vote and approval

I understand, this is basically a reward for me to work twoards, this pr can sit here for 2 years, its for when the community beleives I've done enough to be considered a dev. and worthy of my own model.

**Comment by Limeinade** [comment]
no adding personal models without a community vote, also before saying to add a model, actually do work on the inventory or ttt aspect before doing so, that way it doesn't waste usable space in the server folder

**Comment by V2LenKagamine** [comment]
> this pr can sit here for 2 years, its for when the community beleives I've done enough to be considered a dev. and worthy of my own model.

I can wait. it doesnt need merged asap

**Comment by TheCrossBoy** [comment]
Pull requests aren't meant to be goals to aspire to or sit open, they should be kept clean/organized and are meant for code that should be merged into the server as is

**Pull request closed without merging**
