### PR TITLE
Adds Build-A-Wall: The Magneto Stick replacing Barricade Maker!

### PR DESCRIPTION
**Pull request by V2LenKagamine**
Adds the Build-A-Wall, A Magneto Stick Replacer
Intended Rarity- Unique
Obtain method- Idc really.

Primary: Spawns a 200 Health Barrier at the position located on your client. Faces the way you're rotated. 2 ammo per round, place able every 3 seconds.
Secondary: Locks the location of where you place the barrier, but not its rotation, allowing you to rotate the barrier. You can go as far away as you want to place the barrier, so long as you keep the tool out.
Reload: Rotate the barrier by 90 Degrees, allowing for long chest height barriers or short player height walls.

The barriers stats:
200 HP, a bit longer than a player is tall, and tall enough to hide about 55% of your body standing. If you're crouching, hides you fully. Can be Crouch Jumped over. Can be placed In walls and floors, but _**NOT INSIDE OF OTHER ENTITIES.**_ _If its inside an entity, you can't place the barrier._ Does not move once placed. Looks kinda like a forcefield. Metal Sounds.

Ranting:
I've done a good bit of testing with this. The clientside Model renders accurately to where it will place. In firefights, makes a poor tool, its best used before they start. 200 HP is tanky enough to absorb stray bullets or about 1/2 a mag from most autos to dissuade hitting it, but can still be destroyed quick enough to emphasize getting to real cover. Can be seen through, so you cant quite ambush someone with it. Overall, a useful tools for traitors and innocents alike, if you're willing to give up propkills and picking up props, as it does take up the magneto-stick slot.

Model for barrier *Very Poorly* made by me. Its literally a rectangle. I may come back and make it better though, so I made it an entity you can spawn as admin.

Next In my queue is fixing that stupid shotgun bug, and maybe the tab bug too.

### CODE REVIEW

**Comment by meepen** [comment]
this definitely sounds more of a traitor/detective weapon

**Comment by meepen** [comment]
anyone who disagrees with my previous comment gae

**Comment by meepen** [comment]
also: please use network variables in predicted hooks for position saving

**Comment by V2LenKagamine** [comment]
Do good meepen.

**Pull request closed without merging**
